### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vishavsingla**

### CODE REVIEW

**Review by taran-aujla — APPROVED** [review]

**Review by mayank-0407 — COMMENTED** [review]
Very nice update

**Comment by vishavsingla** [comment]
bhai woh sikha rha tha

**Comment by vishavsingla** [comment]
@mayank-0407

**Comment by taran-aujla** [comment]
THanks

**Comment by mayank-0407** [comment]
Chat Zone

**Pull request merged**
